package org.gauntlet.quizzes.generator.defaults.impl;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import org.gauntlet.core.api.ApplicationException;
import org.gauntlet.core.api.dao.NoSuchModelException;
import org.gauntlet.core.commons.util.jpa.JPAEntityUtil;
import org.gauntlet.problems.api.dao.IProblemDAOService;
import org.gauntlet.problems.api.model.Problem;
import org.gauntlet.problems.api.model.ProblemCategory;
import org.gauntlet.problems.api.model.ProblemDifficulty;
import org.osgi.framework.BundleContext;
import org.osgi.service.log.LogService;
import org.quizzical.backend.security.api.model.user.User;
import org.quizzical.backend.testdesign.api.dao.ITestDesignTemplateDAOService;
import org.quizzical.backend.testdesign.api.model.TestDesignTemplate;
import org.quizzical.backend.testdesign.api.model.TestDesignTemplateItem;
import org.quizzical.backend.testdesign.api.model.TestDesignTemplateItemDifficultyType;
import org.quizzical.backend.testdesign.api.model.TestDesignTemplateSection;
import org.quizzical.backend.testdesign.model.jpa.JPATestDesignTemplateContentSubType;
import org.quizzical.backend.testdesign.model.jpa.JPATestDesignTemplateItem;
import org.gauntlet.quizzes.api.dao.IQuizDAOService;
import org.gauntlet.quizzes.api.model.Constants;
import org.gauntlet.quizzes.api.model.Quiz;
import org.gauntlet.quizzes.api.model.QuizProblem;
import org.gauntlet.quizzes.api.model.QuizProblemType;
import org.gauntlet.quizzes.api.model.QuizType;
import org.gauntlet.quizzes.generator.api.IQuizGeneratorService;
import org.gauntlet.quizzes.generator.api.model.QuizGenerationParameters;


public class PracticeTestGeneratorImpl implements IQuizGeneratorService { 
	private static final DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
	private static final DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");

	private volatile LogService logger;
	
	private volatile BundleContext ctx;

	private volatile IQuizDAOService quizDAOService;
	
	private volatile IProblemDAOService problemDAOService;
	
	private volatile ITestDesignTemplateDAOService testTemplateService;
	
	@Override
	public Quiz generate(User user, QuizGenerationParameters params) throws ApplicationException {
		TestDesignTemplateSection nonCalSec = null;
		TestDesignTemplateSection calSec = null;

		final TestDesignTemplate pt1 = testTemplateService.getByCode("PracticeTest1");
		final List<TestDesignTemplateSection> sections = pt1.getOrderedSections();
		nonCalSec = sections.get(0);
		calSec = sections.get(1);

		//=== Init params
		final QuizType quizType = quizDAOService.provideQuizType(new QuizType(
				Constants.QUIZ_TYPE_GENERATED_NAME,
				Constants.QUIZ_TYPE_GENERATED_CODE));

		final Date quizDateTime = Calendar.getInstance().getTime();
		final String quizName = String.format(
				"Generated by TestDesign \"%s\" at %s on %s",
				pt1.getCode(),
				timeFormat.format(quizDateTime),
				dateFormat.format(quizDateTime));
		
		final String quizCode = String.format(
				"generated-%s-%d-%d",
				params.getGeneratorType(),
				58,
				System.currentTimeMillis());
		
		final Counter counter = new Counter(0);
		
		//=== NonCalc
		Map<Long,Problem> includedProblemIds = new HashMap<>();
		final List<QuizProblem> nonCalcQuizProblems = nonCalSec.getOrderedItems()
				.parallelStream()
        		.map(item -> {
        			QuizProblem qp = null;
        			try {
						ProblemCategory cat = problemDAOService.getProblemCategoryByCode(item.getContentSubType().getCode());
						ProblemDifficulty diff = problemDAOService.getProblemDifficultyByCode(getDifficultyCode(item.getDifficultyType()));
						
						long count = problemDAOService.countByCalcAndDifficultyAndCategoryNotInIn(false,diff.getId(), cat.getId(), new ArrayList<Long>(includedProblemIds.keySet()));
						if (count < 1)
							throw new RuntimeException(String.format("Test Item %s cannot match a problem with reqCalc=%b cat=%s, diff=%s not in [%s]",item.getCode(),false,cat.getCode(),diff.getCode(),includedProblemIds.keySet()));
						int randomOffset = (int)generateRandowOffset(count);
						
						final List<Problem> problems = problemDAOService.findByDifficultyAndCategoryNotInIn(false,diff.getId(), cat.getId(), new ArrayList<Long>(includedProblemIds.keySet()),randomOffset,1);
						if (problems.isEmpty())
							throw new RuntimeException(String.format("Test Item %s cannot match a problem with reqCalc=%b cat=%s, diff=%s not in [%s]",item.getCode(),true,cat.getCode(),diff.getCode(),includedProblemIds.keySet()));
						final Problem problem = problems.iterator().next();
						
						includedProblemIds.put(problem.getId(),problem);
						
						qp = new QuizProblem(
								quizCode,
								counter.incr(),
								item.getSection().getOrdinal(),
								item.getOrdinal(),
								problem.getId(),
								problem);
						System.out.println(qp.getQuizOrdinal());
					} catch (Exception e) {
						StringWriter sw = new StringWriter();
						e.printStackTrace(new PrintWriter(sw));
						String stacktrace = sw.toString();
						System.out.println(e.getMessage());
						//logger.log(LogService.LOG_ERROR,stacktrace);
						//throw new RuntimeException(String.format("Error processing TestDesign item %s",item.getCode()));
					}
        			
        			return qp;
    	    	})
        		.collect(Collectors.toList());
		final Problem startNonCalcProblem = problemDAOService.getByCode(org.gauntlet.problems.api.model.Constants.SYSTEM_PROBLEM_START_NON_CALC_SEC);

		includedProblemIds.put(startNonCalcProblem.getId(),startNonCalcProblem);
		QuizProblem startNonCalcQuizProblem = new QuizProblem(
				quizCode,
				counter.incr(),
				nonCalSec.getOrdinal(),
				-1,
				startNonCalcProblem.getId(),
				startNonCalcProblem);
		startNonCalcQuizProblem.setType(QuizProblemType.INFORMATIONAL);
		System.out.println(startNonCalcQuizProblem.getQuizOrdinal());
		
		
		//=== Calc
		final List<QuizProblem> calcQuizProblems = calSec.getOrderedItems()
				.parallelStream()
        		.map(item -> {
        			QuizProblem qp = null;
        			long count = 0;
						try {
							final ProblemCategory cat = problemDAOService.getProblemCategoryByCode(item.getContentSubType().getCode());
							final ProblemDifficulty diff = problemDAOService.getProblemDifficultyByCode(getDifficultyCode(item.getDifficultyType()));
							
							count = problemDAOService.countByCalcAndDifficultyAndCategoryNotInIn(true,diff.getId(), cat.getId(), new ArrayList<Long>(includedProblemIds.keySet()));
							if (count < 1)
								throw new RuntimeException(String.format("Test Item %s cannot match a problem with reqCalc=%b cat=%s, diff=%s not in [%s]",item.getCode(),true,cat.getCode(),diff.getCode(),includedProblemIds.keySet()));
							int randomOffset = (int)generateRandowOffset(count);
							
							final List<Problem> problems = problemDAOService.findByDifficultyAndCategoryNotInIn(true,diff.getId(), cat.getId(), includedProblemIds.keySet(),randomOffset,1);
							if (problems.isEmpty())
								throw new RuntimeException(String.format("Empty: Test Item %s cannot match a problem with reqCalc=%b cat=%s, diff=%s not in [%s]",item.getCode(),true,cat.getCode(),diff.getCode(),includedProblemIds.keySet()));
							final Problem problem = problems.iterator().next();
							
							includedProblemIds.put(problem.getId(),problem);
							
							
							qp = new QuizProblem(
									quizCode,
									counter.incr(),
									item.getSection().getOrdinal(),
									item.getOrdinal(),
									problem.getId(),
									problem); 
							System.out.println(qp.getQuizOrdinal());
						} catch (Exception e) {
							StringWriter sw = new StringWriter();
							e.printStackTrace(new PrintWriter(sw));
							String stacktrace = sw.toString();
							System.out.println(e.getMessage());
							//logger.log(LogService.LOG_ERROR,stacktrace);
							//throw new RuntimeException(String.format("Error processing TestDesign item %s",item.getCode()));
						}
				
        			
        			return qp;
    	    	})
        		.collect(Collectors.toList());	
		
		final Problem startCalcProblem = problemDAOService.getByCode(org.gauntlet.problems.api.model.Constants.SYSTEM_PROBLEM_START_CALC_SEC);

		includedProblemIds.put(startCalcProblem.getId(),startCalcProblem);
		QuizProblem startCalcQuizProblem = new QuizProblem(
				quizCode,
				counter.incr(),
				calSec.getOrdinal(),
				-1,
				startCalcProblem.getId(),
				startCalcProblem);
		startCalcQuizProblem.setType(QuizProblemType.INFORMATIONAL);
		
		System.out.println(startCalcQuizProblem.getQuizOrdinal());

		
		final List<QuizProblem> orderedQuizProblems = Stream.concat(nonCalcQuizProblems.stream(), calcQuizProblems.stream()).collect(Collectors.toList());
		Collections.sort(orderedQuizProblems, new Comparator<QuizProblem>() {
			@Override
			public int compare(QuizProblem o1, QuizProblem o2) {
				if  (((o1.getSectionOrdinal() < o2.getSectionOrdinal())
						|| o1.getSectionOrdinal() == o2.getSectionOrdinal()) && (
								(o1.getOrdinal() < o2.getOrdinal()))
							||  (o1.getOrdinal() == -1 && o2.getOrdinal() > -1)
						)
					return -1;
				else if (((o1.getSectionOrdinal() > o2.getSectionOrdinal())
						|| o1.getSectionOrdinal() == o2.getSectionOrdinal()) && (
								(o1.getOrdinal() > o2.getOrdinal())
							||  (o1.getOrdinal() > -1 && o2.getOrdinal() == -1)
								)
						)
					return  1;
				else 
					return 0;//they must be the same
			}
		});
		orderedQuizProblems.add(0,startNonCalcQuizProblem);
		orderedQuizProblems.add(nonCalcQuizProblems.size()+1,startCalcQuizProblem);

		
		final Quiz quiz = new Quiz();
		quiz.setUserId(user.getId());
		quiz.setCode(quizCode);
		quiz.setName(quizName);
		quiz.setQuizType(quizType);
		quiz.setQuestions(orderedQuizProblems);
		
		final Quiz persistedQuiz = quizDAOService.provide(user, quiz);
		persistedQuiz.getQuestions()
			.stream()
			.forEach(question -> {
				question.setProblem(includedProblemIds.get(question.getProblemId()));
				question.setQuiz(quiz);
				question.setOrdinal(question.getQuizOrdinal());
			});
		
		return persistedQuiz;
	}

	private long generateRandowOffset(long count) {
		if (count == 0)
			return count;
		return ThreadLocalRandom.current().nextLong(0, count);
	}

	private String getDifficultyCode(TestDesignTemplateItemDifficultyType difficultyType) {
		if (difficultyType.equals(TestDesignTemplateItemDifficultyType.EASY))
			return "Easy";
		else if (difficultyType.equals(TestDesignTemplateItemDifficultyType.MEDIUM))
			return "Medium";
		else
			return "Hard";
	}
	
    public class Counter {

        private final AtomicInteger number;

        public Counter(int number) {
          this.number = new AtomicInteger(number);
        }

        public Integer incr() {
          return number.incrementAndGet();
        }
    }
}